# Generated by Django 5.1.1 on 2024-10-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('experience_years', models.IntegerField()),
                ('available_to_hire', models.BooleanField(default=True)),
                ('join_date', models.DateField()),
            ],
        ),
    ]
