# Generated by Django 5.1.1 on 2024-10-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('platform', models.CharField(choices=[('PC', 'Computer/Laptop'), ('Console', 'Console'), ('Mobile', 'Android/iOS')], default='PC', max_length=7)),
            ],
        ),
    ]
