# Generated by Django 5.1.1 on 2024-11-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gamedeveloper_game_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedeveloper',
            name='role',
            field=models.CharField(choices=[('Level Designer', 'Level Designer'), ('Programmer', 'Programmer'), ('Artist', 'Artist'), ('Animator', 'Animator'), ('Sound Designer', 'Sound Designer'), ('Project Manager', 'Project Manager'), ('UI/UX Designer', 'UI/UX Designer')], max_length=20),
        ),
    ]
